In [1]:
import pandas as pd 
import numpy as np

In [2]:
econ_dis = pd.read_excel("data/econ_disadvantaged.xlsx")

In [3]:
# filter for the three schools being studied
bldg_irns = [729, 24687, 32060]
reduced_econdis = econ_dis[econ_dis['Building IRN'].isin(bldg_irns)]

In [4]:
#replace all NC with NaNs so I can manipulate

reduced_econdis.replace('NC', np.nan, inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\pandas\core\frame.py:3798: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)

In [5]:
#drop all columns with all NA values

reduced_econdis.dropna(axis=1, how='all', inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [6]:
reduced_econdis

,Building IRN,Building Name,Student Group,ELA 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,ELA 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,ELA 5th Grade 2017-2018 % Proficient or above,Math 5th Grade 2017-2018 % Proficient or above,Science 5th Grade 2017-2018 % Proficient or above,ELA 6th Grade 2017-2018 % Proficient or above,Math 6th Grade 2017-2018 % Proficient or above,ELA 7th Grade 2017-2018 % Proficient or above,Math 7th Grade 2017-2018 % Proficient or above,ELA 8th Grade 2017-2018 % Proficient or above,Math 8th Grade 2017-2018 % Proficient or above,Science 8th Grade 2017-2018 % Proficient or above,Attendance Rate 2017-2018,Enrollment 2017-2018,Percent of Total Enrollment 2017-2018
286,729,Andrew J Rickoff,Disadvantaged,5.5,11.3,24.1,51.7,15.6,40.6,18.8,13.0,4.3,14.3,14.3,20.0,13.3,26.7,88.8,441.0,>95
287,729,Andrew J Rickoff,NonDisadvantaged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3648,24687,Miles School,Disadvantaged,22.6,40.0,15.2,10.0,13.9,34.3,40.0,8.1,24.3,20.8,20.8,7.7,11.5,7.7,90.7,420.0,>95
3649,24687,Miles School,NonDisadvantaged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4466,32060,Robert H Jamison School,Disadvantaged,12.2,21.1,13.3,9.4,12.9,10.0,6.9,10.0,10.0,12.1,12.1,7.1,3.6,7.1,93.8,365.0,>95
4467,32060,Robert H Jamison School,NonDisadvantaged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#want to compare with district economically disadvantaged students

In [8]:
district_econ_dis = pd.read_excel("data/district_econdis_1718.xlsx")

In [9]:
cmsd_econdis = district_econ_dis.loc[district_econ_dis["District IRN"] == 43786]

In [10]:
cmsd_econdis

,District IRN,District Name,County,Region,Student Group,Read 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,Read 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,Read 5th Grade 2017-2018 % Proficient or above,...,Geometry End of Course 2017-2018 % Proficient or above,Integrated Math I End of Course 2017-2018 % Proficient or above,Integrated Math II End of Course 2017-2018 % Proficient or above,Biology End of Course 2017-2018 % Proficient or above,Attendance Rate 2017-2018,4-Year Longitudinal Graduation Rate - Class of 2017,5-Year Longitudinal Graduation Rate - Class of 2016,Enrollment,% of Total Enrollment,Watermark
62,43786,Cleveland Municipal,Cuyahoga,Region 3,Disadvantaged,35.4,40.2,36.0,41.5,37.0,...,16.8,NC,NC,45.8,90.9,74.6,79.6,38645,>95.0,NaN
63,43786,Cleveland Municipal,Cuyahoga,Region 3,NonDisadvantaged,87.3,65.5,85.2,85.5,>95.0,...,58.1,NC,NC,80.0,NC,NC,NC,NC,NC,NaN

In [11]:
#replace all NC with NaNs so I can manipulate

cmsd_econdis.replace('NC', np.nan, inplace=True)

#drop all columns with all NA values

cmsd_econdis.dropna(axis=1, how='all', inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [12]:
cmsd_econdis

,District IRN,District Name,County,Region,Student Group,Read 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,Read 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,Read 5th Grade 2017-2018 % Proficient or above,...,English Language Arts I End of Course 2017-2018 % Proficient or,English Language Arts II End of Course 2017-2018 % Proficient or,Algebra I End of Course 2017-2018 % Proficient or above,Geometry End of Course 2017-2018 % Proficient or above,Biology End of Course 2017-2018 % Proficient or above,Attendance Rate 2017-2018,4-Year Longitudinal Graduation Rate - Class of 2017,5-Year Longitudinal Graduation Rate - Class of 2016,Enrollment,% of Total Enrollment
62,43786,Cleveland Municipal,Cuyahoga,Region 3,Disadvantaged,35.4,40.2,36.0,41.5,37.0,...,38.5,35.8,27.2,16.8,45.8,90.9,74.6,79.6,38645,>95.0
63,43786,Cleveland Municipal,Cuyahoga,Region 3,NonDisadvantaged,87.3,65.5,85.2,85.5,>95.0,...,63.2,43.8,56.6,58.1,80.0,NaN,NaN,NaN,NaN,NaN

In [13]:
cmsd_econdis.columns.values

array(['District IRN', 'District Name', 'County', 'Region',
       'Student Group', 'Read 3rd Grade 2017-2018 % Proficient or above',
       'Math 3rd Grade 2017-2018 % Proficient or above',
       'Read 4th Grade 2017-2018 % Proficient or above',
       'Math 4th Grade 2017-2018 % Proficient or above',
       'Read 5th Grade 2017-2018 % Proficient or above',
       'Math 5th Grade 2017-2018 % Proficient or above',
       'Science 5th Grade 2017-2018 % Proficient or above',
       'Read 6th Grade 2017-2018 % Proficient or above',
       'Math 6th Grade 2017-2018 % Proficient or above',
       'Read 7th Grade 2017-2018 % Proficient or above',
       'Math 7th Grade 2017-2018% Proficient or above',
       'Read 8th Grade 2017-2018 % Proficient or above',
       'Math 8th Grade 2017-2018 % Proficient or above',
       'Science 8th Grade 2017-2018 % Proficient or above',
       'History End of Course 2017-2018 % Proficient or above',
       'Government End of Course 2017-2018 % Proficient or above',
       'English Language Arts I End of Course 2017-2018 % Proficient or',
       'English Language Arts II End of Course 2017-2018 % Proficient or',
       'Algebra I End of Course 2017-2018 % Proficient or above',
       'Geometry End of Course 2017-2018 % Proficient or above',
       'Biology End of Course 2017-2018 % Proficient or above',
       'Attendance Rate 2017-2018',
       '4-Year Longitudinal Graduation Rate - Class of 2017',
       '5-Year Longitudinal Graduation Rate - Class of 2016',
       'Enrollment', '% of Total Enrollment'], dtype=object)

In [14]:
# drop columns that aren't relevant to elementary schools 

cmsd_econdis.drop(columns=['County', 'Region', 'History End of Course 2017-2018 % Proficient or above', 'Government End of Course 2017-2018 % Proficient or above', 'English Language Arts I End of Course 2017-2018 % Proficient or', 'English Language Arts II End of Course 2017-2018 % Proficient or', 'Algebra I End of Course 2017-2018 % Proficient or above', 'Geometry End of Course 2017-2018 % Proficient or above', 'Biology End of Course 2017-2018 % Proficient or above', '4-Year Longitudinal Graduation Rate - Class of 2017', '5-Year Longitudinal Graduation Rate - Class of 2016'], inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [15]:
cmsd_econdis

,District IRN,District Name,Student Group,Read 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,Read 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,Read 5th Grade 2017-2018 % Proficient or above,Math 5th Grade 2017-2018 % Proficient or above,Science 5th Grade 2017-2018 % Proficient or above,Read 6th Grade 2017-2018 % Proficient or above,Math 6th Grade 2017-2018 % Proficient or above,Read 7th Grade 2017-2018 % Proficient or above,Math 7th Grade 2017-2018% Proficient or above,Read 8th Grade 2017-2018 % Proficient or above,Math 8th Grade 2017-2018 % Proficient or above,Science 8th Grade 2017-2018 % Proficient or above,Attendance Rate 2017-2018,Enrollment,% of Total Enrollment
62,43786,Cleveland Municipal,Disadvantaged,35.4,40.2,36.0,41.5,37.0,29.4,33.4,25.5,25.2,33.3,27.7,24.2,27.2,33.0,90.9,38645,>95.0
63,43786,Cleveland Municipal,NonDisadvantaged,87.3,65.5,85.2,85.5,>95.0,90.0,76.9,83.8,75.0,>95.0,76.9,66.7,NaN,89.2,NaN,NaN,NaN