In [1]:
import pandas as pd
import numpy as np

In [2]:
disabled_group = pd.read_excel("data/bldg_disabled_1718.xlsx")

In [3]:
disabled_group.head()

,Building IRN,Building Name,District IRN,District Name,Student Group,ELA 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,ELA 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,ELA 5th Grade 2017-2018 % Proficient or above,...,Geometry End of Course 2017-2018 % Proficient or above,Integrated Math I End of Course 2017-2018 % Proficient or above,Integrated Math II End of Course 2017-2018 % Proficient or above,Biology End of Course 2017-2018 % Proficient or above,Four Year Grad Rate 2017,Five Year Grad Rate 2016,Attendance Rate 2017-2018,Enrollment 2017-2018,Percent of Total Enrollment 2017-2018,watermark
0,59,Ada Elementary School,45187,Ada Exempted Village,Disabled,NC,NC,NC,90,50,...,NC,NC,NC,NC,NC,NC,94.6,56,12.4,NaN
1,59,Ada Elementary School,45187,Ada Exempted Village,NonDisabled,87.3,90.9,83,88.7,85.5,...,NC,NC,NC,NC,NC,NC,96.1,396,87.6,NaN
2,67,Ada High School,45187,Ada Exempted Village,Disabled,NC,NC,NC,NC,NC,...,25,NC,NC,NC,90.9,NC,94,36,9.2,NaN
3,67,Ada High School,45187,Ada Exempted Village,NonDisabled,NC,NC,NC,NC,NC,...,59.7,NC,NC,93.8,100,91.9,94.9,356,90.8,NaN
4,83,Sandusky Middle School,44743,Sandusky City,Disabled,NC,NC,NC,NC,NC,...,NC,NC,NC,NC,NC,NC,93.1,74,14.9,NaN

In [4]:
# filter for the three schools being studied
bldg_irns = [729, 24687, 32060]
disabled_3filter = disabled_group[disabled_group['Building IRN'].isin(bldg_irns)]

In [5]:
disabled_3filter

,Building IRN,Building Name,District IRN,District Name,Student Group,ELA 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,ELA 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,ELA 5th Grade 2017-2018 % Proficient or above,...,Geometry End of Course 2017-2018 % Proficient or above,Integrated Math I End of Course 2017-2018 % Proficient or above,Integrated Math II End of Course 2017-2018 % Proficient or above,Biology End of Course 2017-2018 % Proficient or above,Four Year Grad Rate 2017,Five Year Grad Rate 2016,Attendance Rate 2017-2018,Enrollment 2017-2018,Percent of Total Enrollment 2017-2018,watermark
286,729,Andrew J Rickoff,43786,Cleveland Municipal,Disabled,NC,10,NC,NC,NC,...,NC,NC,NC,NC,NC,NC,92.8,93,21.1,NaN
287,729,Andrew J Rickoff,43786,Cleveland Municipal,NonDisabled,6.8,11.6,25,55,19.2,...,NC,NC,NC,NC,NC,NC,87.9,347,78.7,NaN
3648,24687,Miles School,43786,Cleveland Municipal,Disabled,6.3,7.7,NC,NC,NC,...,NC,NC,NC,NC,NC,NC,89.7,98,23.3,NaN
3649,24687,Miles School,43786,Cleveland Municipal,NonDisabled,29.7,51.4,20,13,12.9,...,NC,NC,NC,NC,NC,NC,91,322,76.7,NaN
4466,32060,Robert H Jamison School,43786,Cleveland Municipal,Disabled,16.7,16.7,NC,NC,NC,...,NC,NC,NC,NC,NC,NC,94.7,74,20.3,NaN
4467,32060,Robert H Jamison School,43786,Cleveland Municipal,NonDisabled,10.3,23.1,9.1,NC,8.3,...,NC,NC,NC,NC,NC,NC,93.6,291,79.7,NaN

In [6]:
#replace all NC with NaNs so I can manipulate

disabled_3filter.replace('NC', np.nan, inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\pandas\core\frame.py:3798: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)

In [7]:
#drop all columns with all NA values

disabled_3filter.dropna(axis=1, how='all', inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
disabled_3filter

,Building IRN,Building Name,District IRN,District Name,Student Group,ELA 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,ELA 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,ELA 5th Grade 2017-2018 % Proficient or above,...,ELA 6th Grade 2017-2018 % Proficient or above,Math 6th Grade 2017-2018 % Proficient or above,ELA 7th Grade 2017-2018 % Proficient or above,Math 7th Grade 2017-2018 % Proficient or above,ELA 8th Grade 2017-2018 % Proficient or above,Math 8th Grade 2017-2018 % Proficient or above,Science 8th Grade 2017-2018 % Proficient or above,Attendance Rate 2017-2018,Enrollment 2017-2018,Percent of Total Enrollment 2017-2018
286,729,Andrew J Rickoff,43786,Cleveland Municipal,Disabled,NaN,10.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.8,93,21.1
287,729,Andrew J Rickoff,43786,Cleveland Municipal,NonDisabled,6.8,11.6,25.0,55.0,19.2,...,11.1,5.9,12.5,12.5,27.3,18.2,36.4,87.9,347,78.7
3648,24687,Miles School,43786,Cleveland Municipal,Disabled,6.3,7.7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.7,98,23.3
3649,24687,Miles School,43786,Cleveland Municipal,NonDisabled,29.7,51.4,20.0,13.0,12.9,...,10.0,26.7,21.1,26.3,10.0,15.0,10.0,91.0,322,76.7
4466,32060,Robert H Jamison School,43786,Cleveland Municipal,Disabled,16.7,16.7,NaN,NaN,NaN,...,9.1,9.1,NaN,NaN,NaN,NaN,NaN,94.7,74,20.3
4467,32060,Robert H Jamison School,43786,Cleveland Municipal,NonDisabled,10.3,23.1,9.1,NaN,8.3,...,10.5,10.5,4.2,8.3,9.1,4.5,4.5,93.6,291,79.7

In [9]:
disabled_3filter.drop(columns=['District IRN', 'District Name'], inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [10]:
disabled_3filter

,Building IRN,Building Name,Student Group,ELA 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,ELA 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,ELA 5th Grade 2017-2018 % Proficient or above,Math 5th Grade 2017-2018 % Proficient or above,Science 5th Grade 2017-2018 % Proficient or above,ELA 6th Grade 2017-2018 % Proficient or above,Math 6th Grade 2017-2018 % Proficient or above,ELA 7th Grade 2017-2018 % Proficient or above,Math 7th Grade 2017-2018 % Proficient or above,ELA 8th Grade 2017-2018 % Proficient or above,Math 8th Grade 2017-2018 % Proficient or above,Science 8th Grade 2017-2018 % Proficient or above,Attendance Rate 2017-2018,Enrollment 2017-2018,Percent of Total Enrollment 2017-2018
286,729,Andrew J Rickoff,Disabled,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.8,93,21.1
287,729,Andrew J Rickoff,NonDisabled,6.8,11.6,25.0,55.0,19.2,42.3,19.2,11.1,5.9,12.5,12.5,27.3,18.2,36.4,87.9,347,78.7
3648,24687,Miles School,Disabled,6.3,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.7,98,23.3
3649,24687,Miles School,NonDisabled,29.7,51.4,20.0,13.0,12.9,38.7,45.2,10.0,26.7,21.1,26.3,10.0,15.0,10.0,91.0,322,76.7
4466,32060,Robert H Jamison School,Disabled,16.7,16.7,NaN,NaN,NaN,NaN,NaN,9.1,9.1,NaN,NaN,NaN,NaN,NaN,94.7,74,20.3
4467,32060,Robert H Jamison School,NonDisabled,10.3,23.1,9.1,NaN,8.3,4.3,NaN,10.5,10.5,4.2,8.3,9.1,4.5,4.5,93.6,291,79.7

In [11]:
#disabled students are underperforming by a large margin at Miles

#make graphs to show comparisons

#first split the dataframe by school

# rickoff = disabled_3filter.loc[disabled_3filter['Building IRN'] == 729]
# miles = disabled_3filter.loc[disabled_3filter['Building IRN'] == 24687]
# jamison = disabled_3filter.loc[disabled_3filter['Building IRN'] == 32060]

#=============================================================================

In [12]:
district_disabled = pd.read_excel('data/dist_disabled_1718.xlsx')

In [13]:
cmsd_disabled = district_disabled.loc[district_disabled["District IRN"] == 43786]

In [14]:
#replace all NC with NaNs so I can manipulate

cmsd_disabled.replace('NC', np.nan, inplace=True)

#drop all columns with all NA values

cmsd_disabled.dropna(axis=1, how='all', inplace=True)

C:\Users\Rachael C. Amick\anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [15]:
cmsd_disabled

,District IRN,District Name,Student Group,Read 3rd Grade 2017-2018 % Proficient or above,Math 3rd Grade 2017-2018 % Proficient or above,Read 4th Grade 2017-2018 % Proficient or above,Math 4th Grade 2017-2018 % Proficient or above,Read 5th Grade 2017-2018 % Proficient or above,Math 5th Grade 2017-2018 % Proficient or above,Science 5th Grade 2017-2018 % Proficient or above,Read 6th Grade 2017-2018 % Proficient or above,Math 6th Grade 2017-2018 % Proficient or above,Read 7th Grade 2017-2018 % Proficient or above,Math 7th Grade 2017-2018% Proficient or above,Read 8th Grade 2017-2018 % Proficient or above,Math 8th Grade 2017-2018 % Proficient or above,Science 8th Grade 2017-2018 % Proficient or above,Attendance Rate 2017-2018,Enrollment,% of Total Enrollment
62,43786,Cleveland Municipal,Disabled,21.5,24.8,23.6,26.3,25.8,25.6,24.5,17.8,19.4,21.4,18.9,16.3,16.3,19.8,90.5,8817,22.8
63,43786,Cleveland Municipal,NonDisabled,40.3,45.0,40.7,46.9,41.8,32.0,37.2,29.0,28.0,38.0,30.8,27.1,30.8,38.2,91.0,29828,77.2